# Generated by Django 5.2 on 2026-05-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.FloatField(default=0.0, editable=False, help_text='Average rating from all received seller ratings'),
        ),
    ]
