# Generated by Django 5.2 on 2026-05-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating_count',
            field=models.IntegerField(default=0, editable=False, help_text='Total number of received seller ratings'),
        ),
    ]
