# Generated by Django 5.2 on 2026-03-31 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('items', '0003_claim_remove_purchase_buyer_remove_purchase_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'owner', 'category'), name='unique_item_name_owner_category'),
        ),
    ]
