# Generated by Django 5.2 on 2026-06-10 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_unique_item_name_owner_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_name_owner_category',
        ),
    ]
