# Generated by Django 5.2 on 2026-08-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin resolution notes'),
        ),
    ]
